[build]
target = "aarch64-unknown-none-softfloat"

[target.aarch64-unknown-none-softfloat]
rustflags = ["-C", "link-arg=-Tlink.ld", "-C", "target-cpu=cortex-a53"]
runner = "qemu-system-aarch64 -M raspi3 -serial stdio -display none -kernel"
